# File: .github/workflows/train_ci.yml
name: MLflow CI Automation and Docker Build Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'Workflow-CI/**' # Berjalan otomatis jika ada perubahan di folder Workflow-CI
  workflow_dispatch: # Mengizinkan trigger manual lewat tombol klik di GitHub

permissions:
  contents: write

jobs:
  mlflow-ci-job:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v4

    - name: 2. Setup Python Runtime
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas numpy scikit-learn matplotlib seaborn

    - name: 4. Run MLflow Project (Re-training Model)
      env:
        DAGSHUB_CLIENT_TOKEN: ${{ secrets.DAGSHUB_TOKEN }} # DagsHub token untuk MLflow client
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}   # Token untuk library dagshub.init()
        MLFLOW_ALLOW_FILE_STORE: true                      # Mengizinkan penulisan lokal mlruns pada MLflow versi 2026
      run: |
        cd Workflow-CI/MLProject
        # Menghubungkan pelacakan langsung ke folder mlruns lokal agar folder fisik terbentuk
        export MLFLOW_TRACKING_URI=mlruns
        # PERBAIKAN UTAMA: Mengeksekusi python langsung untuk menghindari konflik Nested Run ID
        python modelling.py

    - name: 5. Build Docker Image via MLflow Build-Docker (ADVANCE Syarat)
      env:
        MLFLOW_ALLOW_FILE_STORE: true                      # Pengaman bypass filestore saat kompilasi image
      run: |
        echo "[+] Mengompilasi Docker Image langsung menggunakan root MLProject..."
        # Menggunakan folder induk MLProject yang berisi manifest sebagai cetak biru kontainer
        mlflow models build-docker -m "Workflow-CI/MLProject" -n "agungprayuda/student-performance-model:latest" --enable-mlserver

    - name: 6. Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} # Memanggil username dari GitHub Secrets
        password: ${{ secrets.DOCKERHUB_TOKEN }}    # Memanggil Access Token dari GitHub Secrets

    - name: 7. Push Docker Image to Docker Hub Repo
      run: |
        docker push agungprayuda/student-performance-model:latest

    - name: 8. Save Artifact Back to Same GitHub Repository (SKILLED Syarat)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: automated ci pipeline artifact upload [skip ci]"
        file_pattern: 'Workflow-CI/MLProject/mlruns/**'
